# Generated by Django 5.2.17 on 2026-09-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ('-created_at',)},
        ),
    ]
