# Generated by hand for the sourcing desk.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_storeproduct_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="sync_status",
            field=models.CharField(
                choices=[("idle", "Idle"), ("ok", "Synced"), ("failed", "Failed")],
                default="idle",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("pending_review", "Pending review"),
                    ("restricted", "Restricted"),
                ],
                default="compliant",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="compliance_notes",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
