# Generated by Django 5.2.17 on 2026-09-24 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('growth', 'Growth')], default='trial', max_length=20)),
                ('custom_domain', models.CharField(blank=True, help_text='Optional storefront hostname, for example shop.example.com.', max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('niche', models.CharField(default='beauty', max_length=64)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False, help_text='Used when an authenticated request omits X-Tenant-Slug.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['status', 'plan'], name='tenants_ten_status_1a8df6_idx'), models.Index(fields=['owner', 'slug'], name='tenants_ten_owner_i_c9cab0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='tenants_one_default_store_per_owner')],
            },
        ),
    ]
